git-commit-setup-font-lock: Demote errors
Any error in git-commit-setup-font-lock will cause committing to fail
with something like:

   1 git … commit --
   hint: Waiting for your editor to close the file...
   Waiting for Emacs...
   *ERROR*: ...
   error: There was a problem with the editor '/path/to/emacsclient --socket-name=...'
   Please supply the message using either -m or -F option.

Demote these errors to messages to prevent committing from failing due
to any error related to font locking.

Re: magit/with-editor#106